version: '3' 
services:
  info:
    image: docker.shaped.ch/microprofile-info
    hostname: info
    networks:
      - mpdemo
    ports:
      - 8180:8080
    environment:
      - JAEGER_SERVICE_NAME=thorntail
      - JAEGER_REPORTER_LOG_SPANS=true 
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1 

  prometheus:
    image: prom/prometheus
    hostname: prometheus
    networks:
      - mpdemo
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    hostname: grafana
    networks:
      - mpdemo
    ports:
      - 9091:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./config/grafana/dashboards/:/opt/dashboards
      - ./config/grafana/custom.yaml:/etc/grafana/provisioning/dashboards/custom.yaml
      - ./config/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  swaggerui:
    image: swaggerapi/swagger-ui
    hostname: swaggerui
    networks:
      - mpdemo
    ports:
      - 9092:8080
    environment:
      - API_URL=http://generator.swagger.io/api/swagger.json
      - URL=http://localhost:8180/openapi

  jaeger:
    image: jaegertracing/all-in-one
    hostname: jaeger
    networks:
      - mpdemo
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 9093:16686

networks:
  mpdemo:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.50.0/24

