{
 "title": "Microprofile Metrics",
 "description": "Metrics on the Microprofile Demo service",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "InfoService /metrics",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=\"info:8080\",job=\"info\"}"
    }
   ]
  },
  {
   "title": "GreeterService /metrics",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=\"greeter:8080\",job=\"greeter\"}"
    }
   ]
  },
  { "title": "InfoService Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Number of /info requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application:info_requests{instance=\"info:8080\",job=\"info\"}",
     "legendFormat": "# GET /info"
    }
   ]
  },
  {
   "title": "Mean /info in sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application:info_timed_mean_seconds{instance=\"info:8080\",job=\"info\"}",
     "legendFormat": "Mean in Sec of GET /info"
    }
   ]
  },
  {
   "title": "Heap memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base:memory_used_heap_bytes{instance=\"info:8080\",job=\"info\"}",
     "legendFormat": "Info"
    }
   ]
  },
  {
   "title": "System load average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base:cpu_system_load_average{instance=\"info:8080\",job=\"info\"}",
     "legendFormat": "Info"
    }
   ]
  },
  {
   "title": "Loaded classes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base:classloader_current_loaded_class_count{instance=\"info:8080\",job=\"info\"}",
     "legendFormat": "Info"
    }
   ]
  },
  {
   "title": "Thread count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base:thread_count{instance=\"info:8080\",job=\"info\"}",
     "legendFormat": "Info"
    }
   ]
  }
 ]
}